# Generated by Django 2.0.7 on 2018-07-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CantDownToDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('name', models.CharField(blank=True, max_length=45, null=True, verbose_name='名字')),
                ('code', models.CharField(blank=True, max_length=45, null=True, verbose_name='代码')),
            ],
            options={
                'verbose_name': 'CantDownToDay',
                'verbose_name_plural': 'CantDownToDay',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='CantDownToDayAfter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('name', models.CharField(blank=True, max_length=45, null=True, verbose_name='名字')),
                ('code', models.CharField(blank=True, max_length=45, null=True, verbose_name='代码')),
            ],
            options={
                'verbose_name': 'CantDownToDayAfter',
                'verbose_name_plural': 'CantDownToDayAfter',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='CantUpToDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('name', models.CharField(blank=True, max_length=45, null=True, verbose_name='名字')),
                ('code', models.CharField(blank=True, max_length=45, null=True, verbose_name='代码')),
            ],
            options={
                'verbose_name': 'CantUpToDay',
                'verbose_name_plural': 'CantUpToDay',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='CantUpToDayAfter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('name', models.CharField(blank=True, max_length=45, null=True, verbose_name='名字')),
                ('code', models.CharField(blank=True, max_length=45, null=True, verbose_name='代码')),
            ],
            options={
                'verbose_name': 'CantUpToDayAfter',
                'verbose_name_plural': 'CantUpToDayAfter',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='CapitalFly1000',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('topic', models.CharField(blank=True, max_length=45, null=True, verbose_name='炒作主题')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TodayReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('sz1A0001', models.CharField(blank=True, max_length=10, null=True, verbose_name='上证指')),
                ('zdf_1a0001', models.CharField(blank=True, max_length=10, null=True, verbose_name='上证指涨跌幅')),
                ('sh399001', models.CharField(blank=True, max_length=10, null=True, verbose_name='深圳指')),
                ('zdf_399001', models.CharField(blank=True, max_length=10, null=True, verbose_name='深圳指涨跌幅')),
                ('up_to_down', models.CharField(blank=True, max_length=10, null=True, verbose_name='昨日涨停今日受益')),
                ('ratio', models.CharField(blank=True, max_length=10, null=True, verbose_name='涨跌比')),
                ('level', models.CharField(blank=True, max_length=10, null=True, verbose_name='大盘评级')),
                ('up', models.CharField(blank=True, max_length=10, null=True, verbose_name='上涨数')),
                ('down', models.CharField(blank=True, max_length=10, null=True, verbose_name='下跌数')),
                ('cant_up', models.CharField(blank=True, max_length=10, null=True, verbose_name='涨停数')),
                ('cant_down', models.CharField(blank=True, max_length=10, null=True, verbose_name='跌停数')),
            ],
            options={
                'verbose_name': 'TodayReport',
                'verbose_name_plural': 'TodayReport',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('topic', models.CharField(blank=True, max_length=45, null=True, verbose_name='炒作主题')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topic',
                'ordering': ['-create_time'],
            },
        ),
    ]
