# Generated by Django 2.0.7 on 2018-07-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalFlyBig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('name', models.CharField(blank=True, max_length=45, null=True, verbose_name='名字')),
                ('code', models.CharField(blank=True, max_length=45, null=True, verbose_name='代码')),
            ],
            options={
                'verbose_name': 'CapitalFlyBig',
                'verbose_name_plural': 'CapitalFlyBig',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='CapitalFly1000',
            options={'ordering': ['-create_time'], 'verbose_name': 'CapitalFly1000', 'verbose_name_plural': 'CapitalFly1000'},
        ),
        migrations.RemoveField(
            model_name='CapitalFly1000',
            name='topic',
        ),
        migrations.AddField(
            model_name='CapitalFly1000',
            name='code',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='代码'),
        ),
        migrations.AddField(
            model_name='CapitalFly1000',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='名字'),
        ),
    ]
